export type stringState = {
  loading: boolean;
  stringAll: Array<{
    child: Array<{
      equipmentCosts: number;
      estimatedProfit: number;
      id: number;
      machineOperatorSalary: number;
      mainCosts: number;
      materials: number;
      mimExploitation: number;
      overheads: number;
      rowName: string;
      salary: number;
      supportCosts: number;
      total: number;
      child: Array<{
        equipmentCosts: number;
        estimatedProfit: number;
        id: number;
        machineOperatorSalary: number;
        mainCosts: number;
        materials: number;
        mimExploitation: number;
        overheads: number;
        rowName: string;
        salary: number;
        supportCosts: number;
        total: number;
      }>;
    }>;
    equipmentCosts: number;
    estimatedProfit: number;
    id: number;
    machineOperatorSalary: number;
    mainCosts: number;
    materials: number;
    mimExploitation: number;
    overheads: number;
    rowName: string;
    salary: number;
    supportCosts: number;
    total: number;
  }>;
};

export type getString = Array<{
  child: Array<{
    equipmentCosts: number;
    estimatedProfit: number;
    id: number;
    machineOperatorSalary: number;
    mainCosts: number;
    materials: number;
    mimExploitation: number;
    overheads: number;
    rowName: string;
    salary: number;
    supportCosts: number;
    total: number;
    child: Array<{
      equipmentCosts: number;
      estimatedProfit: number;
      id: number;
      machineOperatorSalary: number;
      mainCosts: number;
      materials: number;
      mimExploitation: number;
      overheads: number;
      rowName: string;
      salary: number;
      supportCosts: number;
      total: number;
    }>;
  }>;
  equipmentCosts: number;
  estimatedProfit: number;
  id: number;
  machineOperatorSalary: number;
  mainCosts: number;
  materials: number;
  mimExploitation: number;
  overheads: number;
  rowName: string;
  salary: number;
  supportCosts: number;
  total: number;
}>;

export type typeAllString = {
  child: Array<{
    equipmentCosts: number;
    estimatedProfit: number;
    id: number;
    machineOperatorSalary: number;
    mainCosts: number;
    materials: number;
    mimExploitation: number;
    overheads: number;
    rowName: string;
    salary: number;
    supportCosts: number;
    total: number;
    child: Array<{
      equipmentCosts: number;
      estimatedProfit: number;
      id: number;
      machineOperatorSalary: number;
      mainCosts: number;
      materials: number;
      mimExploitation: number;
      overheads: number;
      rowName: string;
      salary: number;
      supportCosts: number;
      total: number;
    }>;
  }>;
  equipmentCosts: number;
  estimatedProfit: number;
  id: number;
  machineOperatorSalary: number;
  mainCosts: number;
  materials: number;
  mimExploitation: number;
  overheads: number;
  rowName: string;
  salary: number;
  supportCosts: number;
  total: number;
};

export type typeSubString = {
  child: Array<{
    equipmentCosts: number;
    estimatedProfit: number;
    id: number;
    machineOperatorSalary: number;
    mainCosts: number;
    materials: number;
    mimExploitation: number;
    overheads: number;
    rowName: string;
    salary: number;
    supportCosts: number;
    total: number;
  }>;
  equipmentCosts: number;
  estimatedProfit: number;
  id: number;
  machineOperatorSalary: number;
  mainCosts: number;
  materials: number;
  mimExploitation: number;
  overheads: number;
  rowName: string;
  salary: number;
  supportCosts: number;
  total: number;
};
export type typeLastString = {
  equipmentCosts: number;
  estimatedProfit: number;
  id: number;
  machineOperatorSalary: number;
  mainCosts: number;
  materials: number;
  mimExploitation: number;
  overheads: number;
  rowName: string;
  salary: number;
  supportCosts: number;
  total: number;
};
